name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: npm install yarn
        run: npm install yarn
      - name: Install dependencies
        run: yarn install
      - name: Build and test
        run: yarn run build
      
